version: '3.1'

services:
  db:
    image: mysql
    container_name: voting_database_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ../docker-volumes/mysql:/var/lib/mysql
      - ../docker-volumes/mysql-conf:/etc/mysql/conf.d
      - ./voting/src/main/resources/sql:/docker-entrypoint-initdb.d
  cache:
    image: redis:6.2-alpine
    container_name: voting_cache_redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ../docker-volumes/redis:/data
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: voting_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafkabroker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: voting_kafka_broker
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafkabroker:9092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkabroker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  voting_app:
    platform: linux/amd64
    container_name: voting_microservice
    build: ./voting
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dockercompose
  receivevote_app:
    platform: linux/amd64
    container_name: receivevote_microservice
    build: ./receivevote
    depends_on:
      - kafkabroker
    links:
      - kafkabroker
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dockercompose