server:
  port: 8080
  servlet:
    context-path: /votings/v1

kafka:
  topic:
    new-vote: votings.vote.new

spring:
  application:
    name: votings-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://db:3306/voting

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE