server:
  port: 0
kafka:
  topic:
    new-vote: votings.vote.new
    process-vote: votings.vote.process

voting-api:
  url: http://localhost:8080
  path: /votings/v1/votings

spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: validate-vote-app
  kafka:
    listener:
      ack-mode: MANUAL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      bootstrap-servers: localhost:29092
    consumer:
      group-id: votes-validator
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: io.github.margato.vs.*
        spring.json.type.mapping: io.github.margato.vs.receivevote.boundaries.messaging.dtos.KafkaMessage:io.github.margato.vs.validatevote.boundaries.messaging.dtos.KafkaMessage
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
