server:
  port: 0
kafka:
  topic:
    process-vote: votings.vote.process

spring:
  application:
    name: voteconsolidation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_ENDPOINT}:3306/voting
  kafka:
    listener:
      ack-mode: MANUAL
    consumer:
      group-id: votes-consolidation
      bootstrap-servers: kafkabroker:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: io.github.margato.vs.*
        spring.json.type.mapping: io.github.margato.vs.validatevote.boundaries.messaging.dtos.KafkaMessage:io.github.margato.vs.voteconsolidation.boundaries.messaging.dtos.KafkaMessage
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 100
